### ISSUE TITLE
Use proper options when running CATs on Eirini

### ISSUE THREAD

**Issue by jimmykarily** [cloudfoundry-incubator/kubecf#1007]
**Is your feature request related to a problem? Please describe.**
CATs fail on Eirini. We need to run only CATs that make sense and should be green when running on Eirini deployments.

**Describe the solution you'd like**
Look here on how this can be implemented:
(https://github.com/SUSE/catapult/blob/master/modules/tests/kubecf-test.sh#L139).

**Comment by jimmykarily** [comment]
Upstream eirini team was using these: https://github.com/cloudfoundry-incubator/eirini-ci/blob/09dcce6d9e900f693dfc1a6da70b5a526cf7de18/pipelines/dhall-modules/jobs/run-core-cats.dhall#L52-L86

**Comment by jimmykarily** [comment]
Started adding support for the Eirini cats suite here: https://github.com/SUSE/catapult/commits/cats_eirini

**Comment by jimmykarily** [comment]
capi_experimental has been removed: https://github.com/cloudfoundry/cf-acceptance-tests/pull/383/commits/00fe329ab742a9ce31039d627e3aa62c95e607a1

Running `v3` should be enough.

**Comment by jimmykarily** [comment]
`credhub` has been replaced by: `credhub_mode`, `credhub_location`, `credhub_client`, `credhub_secret`


https://github.com/cloudfoundry/cf-acceptance-tests/commit/0823b205764bdedb720f5a94a627b6e6c1f0beba
https://github.com/cloudfoundry/cf-acceptance-tests/commit/e28bfaed9e5fd2154580ae53b223ecd865eed131

**Comment by jimmykarily** [comment]
I'm debugging and fixing various CAT failures here: https://github.com/jimmykarily/cf-acceptance-tests/compare/master..fix_eirini_cats

For now I'm finding workarounds trying to understand what the problem is. Before we try to upstream we need proper fixes for all problems (e.g. the loggregator bridge missing logs).

**Comment by jbuns** [comment]
Test results summary so far:

`Summarizing 11 Failures:

[Fail] [apps] Environment Variables Groups Staging environment variable groups [It] Applies environment variables while staging apps
/../cf-acceptance-tests/apps/environment_variables_group.go:135

[Fail] [apps] Healthcheck when the healthcheck is set to none [It] starts up successfully
/../cf-acceptance-tests/apps/healthcheck.go:50

[Fail] [credhub] service bindings during staging [BeforeEach] [non-assisted credhub]  still contains CredHub references in VCAP_SERVICES
/../cf-acceptance-tests/credhub/service_bindings.go:121

[Fail] [credhub] service bindings during staging [BeforeEach] [assisted credhub]  has CredHub references in VCAP_SERVICES interpolated
/../cf-acceptance-tests/credhub/service_bindings.go:121

[Fail] [credhub] service bindings during runtime service bindings to credhub enabled broker [assisted credhub]  [BeforeEach] the broker returns credhub-ref in the credentials block
/../cf-acceptance-tests/credhub/service_bindings.go:121

[Fail] [credhub] service bindings during runtime service bindings to credhub enabled broker [assisted credhub]  [BeforeEach] the bound app gets CredHub refs in VCAP_SERVICES interpolated
/../cf-acceptance-tests/credhub/service_bindings.go:121

[Fail] [credhub] service keys when a service key for a service instance is requested from a CredHub-enabled broker [It] Cloud Controller retrieves the value from CredHub for the service key
/../cf-acceptance-tests/credhub/service_keys.go:96

[Fail] [apps] loggregator cf logs [It] exercises basic loggregator behavior
/Users/jeffreybunagan/lahat/workspace/cf-acceptance-tests/apps/loggregator.go:84

[Fail] [apps] loggregator cf logs --recent [It] makes loggregator buffer and dump log messages
/../cf-acceptance-tests/apps/loggregator.go:94

[Fail] [apps] Logging Syslog drains [It] forwards app messages to registered syslog drains
/../cf-acceptance-tests/apps/syslog_drain.go:141

[Fail] [apps] Buildpack cache [It] uses the buildpack cache after first staging
/../cf-acceptance-tests/apps/buildpack_cache.go:144

Ran 57 of 211 Specs in 1962.438 seconds
FAIL! -- 46 Passed | 11 Failed | 1 Pending | 153 Skipped`

Using config json:

`{
  "api": "api.kubecf-ci-more-cats-eirini-0-0-3.gcpenv.dev",
  "apps_domain": "kubecf-ci-more-cats-eirini-0-0-3.gcpenv.dev",
  "admin_user": "admin",
  "admin_password": "..",
  "artifacts_directory": "logs",
  "skip_ssl_validation": true,
  "timeout_scale": 4,
  "use_http": true,
  "use_log_cache": true,
  "include_apps": true,
  "include_backend_compatibility": false,
  "include_capi_no_bridge": false,
  "include_container_networking": false,
  "credhub_mode" : "assisted",
  "credhub_client": "credhub_admin_client",
  "credhub_secret": "..",
  "include_detect": false,
  "include_docker": false,
  "include_internet_dependent": false,
  "include_internetless": false,
  "include_isolation_segments": false,
  "include_private_docker_registry": false,
  "include_route_services": false,
  "include_routing": false,
  "include_tcp_routing": false,
  "include_routing_isolation_segments": false,
  "include_security_groups": false,
  "include_service_discovery": false,
  "include_services": false,
  "include_service_instance_sharing": false,
  "include_ssh": false,
  "include_sso": false,
  "include_tasks": false,
  "include_v3": false,
  "include_zipkin": false,
  "include_credhub": false,
  "include_volume_services": false,
  "stacks": [
    "sle15"
  ]
}
`

**Comment by jbuns** [comment]
`cf tail` is not a command available for eirini.

Needed to add entry to config json to force to use `cf logs`

`  "use_log_cache": false`

Test results summary after fix:

```
Summarizing 6 Failures:

[Fail] [credhub] service bindings during staging [BeforeEach] [non-assisted credhub]  still contains CredHub references in VCAP_SERVICES 
/../cf-acceptance-tests/credhub/service_bindings.go:121

[Fail] [credhub] service bindings during staging [BeforeEach] [assisted credhub]  has CredHub references in VCAP_SERVICES interpolated 
/../cf-acceptance-tests/credhub/service_bindings.go:121

[Fail] [credhub] service bindings during runtime service bindings to credhub enabled broker [assisted credhub]  [BeforeEach] the broker returns credhub-ref in the credentials block 
/../cf-acceptance-tests/credhub/service_bindings.go:121

[Fail] [credhub] service bindings during runtime service bindings to credhub enabled broker [assisted credhub]  [BeforeEach] the bound app gets CredHub refs in VCAP_SERVICES interpolated 
/../cf-acceptance-tests/credhub/service_bindings.go:121

[Fail] [apps] Buildpack cache [It] uses the buildpack cache after first staging 
/../cf-acceptance-tests/apps/buildpack_cache.go:144

[Fail] [credhub] service keys when a service key for a service instance is requested from a CredHub-enabled broker [It] Cloud Controller retrieves the value from CredHub for the service key 
/../cf-acceptance-tests/credhub/service_keys.go:96

Ran 57 of 211 Specs in 1794.535 seconds
FAIL! -- 51 Passed | 6 Failed | 1 Pending | 153 Skipped
```

**Comment by jbuns** [comment]
Tried recreating scenario of creating credhub service-broker, create service, binding service that results in failing `/../cf-acceptance-tests/credhub/service_bindings.go:121`

`cf bind-service` fails and the logs of the service broker is:

```
2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT credhub client configuration failed: Get https://credhub.service.cf.internal:8844/info: dial tcp: lookup credhub.service.cf.internal on 172.21.0.10:53: no such host
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT 2020/07/08 16:53:29 http: panic serving 172.30.246.75:57704: runtime error: invalid memory address or nil pointer dereference
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT goroutine 111 [running]:
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT net/http.(*conn).serve.func1(0xc000182320)
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT /tmp/contents119306453/deps/0/go1.13.10/src/net/http/server.go:1767 +0x13b
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT panic(0x55de4b9bfc60, 0x55de4bc1db60)
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT /tmp/contents119306453/deps/0/go1.13.10/src/runtime/panic.go:679 +0x1b6
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT go-online/vendor/code.cloudfoundry.org/credhub-cli/credhub.(*CredHub).Request(...)
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT /tmp/gobuildpack.gopath670427482/.go/src/go-online/vendor/code.cloudfoundry.org/credhub-cli/credhub/request.go:22
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT go-online/vendor/code.cloudfoundry.org/credhub-cli/credhub.(*CredHub).setCredential(0x0, 0xc00024c120, 0x13, 0x55de4b67ef71, 0x4, 0x55de4b9bf7e0, 0xc00022a450, 0x55de4b994360, 0xc0002360f0, 0x0, ...)
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT /tmp/gobuildpack.gopath670427482/.go/src/go-online/vendor/code.cloudfoundry.org/credhub-cli/credhub/set.go:83 +0x1be
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT go-online/vendor/code.cloudfoundry.org/credhub-cli/credhub.(*CredHub).SetJSON(...)
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT /tmp/gobuildpack.gopath670427482/.go/src/go-online/vendor/code.cloudfoundry.org/credhub-cli/credhub/set.go:24
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT main.(*ServiceBroker).Bind(0xc0000a4030, 0x55de4ba3a240, 0xc0001660e0, 0xc000179d00)
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT /tmp/gobuildpack.gopath670427482/.go/src/go-online/main.go:126 +0x4ed
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT net/http.HandlerFunc.ServeHTTP(0xc000087020, 0x55de4ba3a240, 0xc0001660e0, 0xc000179d00)
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT /tmp/contents119306453/deps/0/go1.13.10/src/net/http/server.go:2007 +0x46
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT go-online/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000a8190, 0x55de4ba3a240, 0xc0001660e0, 0xc000179d00)
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT /tmp/gobuildpack.gopath670427482/.go/src/go-online/vendor/github.com/gorilla/mux/mux.go:114 +0xdd
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT net/http.(*ServeMux).ServeHTTP(0x55de4bc68240, 0x55de4ba3a240, 0xc0001660e0, 0xc000179b00)
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT /tmp/contents119306453/deps/0/go1.13.10/src/net/http/server.go:2387 +0x1bf
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT net/http.serverHandler.ServeHTTP(0xc00012e000, 0x55de4ba3a240, 0xc0001660e0, 0xc000179b00)
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT /tmp/contents119306453/deps/0/go1.13.10/src/net/http/server.go:2802 +0xa6
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT net/http.(*conn).serve(0xc000182320, 0x55de4ba3aa80, 0xc000063dc0)
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT /tmp/contents119306453/deps/0/go1.13.10/src/net/http/server.go:1890 +0x877
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT created by net/http.(*Server).Serve
   2020-07-08T17:53:29.00+0100 [APP/PROC/WEB/0] OUT /tmp/contents119306453/deps/0/go1.13.10/src/net/http/server.go:2928 +0x386
   2020-07-08T17:53:29.01+0100 [RTR/0] OUT CATS-3-BRKR-CH-cf4f5d96b93cbeb6.ocp-ic-test-sm.kubecf.dev - [2020-07-08T16:53:28.989763357Z] "PUT /v2/service_instances/b421f961-ee37-4655-86af-4fb0cdbc3eae/service_bindings/4db6b3d3-7c09-469c-b186-3a830ef24f41?accepts_incomplete=true HTTP/1.1" 502 585 67 "-" "HTTPClient/1.0 (2.8.3, ruby 2.5.5 (2019-03-15))" "172.30.26.234:39748" "172.30.246.126:8080" x_forwarded_for:"10.113.2.248, 172.30.26.234" x_forwarded_proto:"https" vcap_request_id:"7a231a17-ffd8-4e18-742e-8b825ec12712" response_time:0.022398 gorouter_time:0.000239 app_id:"3eb8c0f2-7882-4bb9-94a9-0a6b9ee4015c" app_index:"-" x_b3_traceid:"c8111d3de536c178" x_b3_spanid:"c8111d3de536c178" x_b3_parentspanid:"-" b3:"c8111d3de536c178-c8111d3de536c178"
   2020-07-08T17:53:29.01+0100 [RTR/0] OUT 
   2020-07-08T17:53:30.00+0100 [APP/PROC/WEB/0] OUT credhub client configuration failed: Get https://credhub.service.cf.internal:8844/info: dial tcp: lookup credhub.service.cf.internal on 172.21.0.10:53: no such host
```

What's interesting is that CATs in eirini runs through this scenario but it doesn't with diego.

**Comment by jbuns** [comment]
Tried running tests only with `include_tasks=true`.

Test results summary:
```
Summarizing 7 Failures:

[Fail] [tasks] v3 tasks tasks lifecycle When cancelling a task [It] should show task is in FAILED state 
/../cf-acceptance-tests/tasks/task.go:210

[Fail] [tasks] v3 tasks tasks lifecycle [It] can successfully create and run a task 
/../cf-acceptance-tests/tasks/task.go:175

[Fail] [credhub] service bindings during staging [BeforeEach] [non-assisted credhub]  still contains CredHub references in VCAP_SERVICES 
/../cf-acceptance-tests/credhub/service_bindings.go:121

[Fail] [credhub] service bindings during staging [BeforeEach] [assisted credhub]  has CredHub references in VCAP_SERVICES interpolated 
/../cf-acceptance-tests/credhub/service_bindings.go:121

[Fail] [credhub] service bindings during runtime service bindings to credhub enabled broker [assisted credhub]  [BeforeEach] the broker returns credhub-ref in the credentials block 
/../cf-acceptance-tests/credhub/service_bindings.go:121

[Fail] [credhub] service bindings during runtime service bindings to credhub enabled broker [assisted credhub]  [BeforeEach] the bound app gets CredHub refs in VCAP_SERVICES interpolated 
/../cf-acceptance-tests/credhub/service_bindings.go:121

[Fail] [credhub] service keys when a service key for a service instance is requested from a CredHub-enabled broker [It] Cloud Controller retrieves the value from CredHub for the service key 
/../cf-acceptance-tests/credhub/service_keys.go:96

Ran 7 of 211 Specs in 638.465 seconds
FAIL! -- 0 Passed | 7 Failed | 1 Pending | 203 Skipped
```

Recreated the tests locally and failing at the same point with task stuck in `CANCELING` after `cf terminate-task` and task stuck in `RUNNING` when it should have been finished:
```
cf tasks CATS-3-APP-3a340794b7d6d78a
Getting tasks for app CATS-3-APP-3a340794b7d6d78a in org CATS-3-ORG-1d0f1d17e8ed40bd / space CATS-3-SPACE-5a4573542cf3c9e8 as admin...
OK

id   name        state       start time                      command
5    meeeeowww   RUNNING     Thu, 09 Jul 2020 14:59:44 UTC   sleep 10;
4    meowww      RUNNING     Thu, 09 Jul 2020 14:53:06 UTC   sleep 100;
3    meow        CANCELING   Thu, 09 Jul 2020 14:29:27 UTC   sleep 100;
2    mreow       CANCELING   Thu, 09 Jul 2020 14:22:17 UTC   sleep 100;
1    ab8d0e40    CANCELING   Thu, 09 Jul 2020 14:20:29 UTC   sleep
```

As previously noted this tests only exists in eirini cats but not in diego cats.
`cf terminate-task` in eirni cats:
https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/cf-acceptance-tests-eirini-master/builds/18#L5efb51ba:15235
Diego cats (none):
https://concourse.suse.dev/teams/main/pipelines/kubecf/jobs/cf-acceptance-tests-diego-master/builds/18

**Comment by jbuns** [comment]
> credhub can't be disabled anymore?
> 
> cloudfoundry/cf-acceptance-tests@0823b20
> cloudfoundry/cf-acceptance-tests@e28bfae

@jimmykarily removing the config entries for credhub in config json seems to be the way to disable credhub tests, although not very obvious from docs.
https://github.com/jimmykarily/cf-acceptance-tests/blob/master/cats_suite_helpers/cats_suite_helpers.go#L256

This reduced the number of failings tests from 16 down to 10:
```
Summarizing 10 Failures:

[Fail] [v3] buildpack With a single buildpack app [It] Downloads the correct user specified git buildpack 
/../cf-acceptance-tests/v3/buildpacks.go:88

[Fail] [v3] buildpack With a single buildpack app [It] uses buildpack cache for staging 
/../cf-acceptance-tests/v3/buildpacks.go:108

[Fail] [v3] v3 docker app lifecycle [It] can run apps 
/../cf-acceptance-tests/helpers/v3_helpers/v3.go:478

[Fail] [tcp routing] TCP Routing external ports [It] maps a single external port to an application's container port 
/../cf-acceptance-tests/tcp_routing/tcp_routing.go:74

[Fail] [tcp routing] TCP Routing external ports with a second external port [It] maps both ports to the same application 
/../cf-acceptance-tests/tcp_routing/tcp_routing.go:127

[Fail] [tcp routing] TCP Routing external ports with two different apps [It] maps single external port to both applications 
/../cf-acceptance-tests/tcp_routing/tcp_routing.go:112

[Fail] [apps] Buildpack cache [It] uses the buildpack cache after first staging 
/../cf-acceptance-tests/apps/buildpack_cache.go:144

[Fail] [docker] Docker Application Lifecycle [JustBeforeEach] running a docker app with a start command retains its start command through starts and stops 
/../cf-acceptance-tests/docker/docker_lifecycle.go:30

[Fail] [docker] Docker Application Lifecycle [JustBeforeEach] running a docker app without a start command handles docker-defined metadata and environment variables correctly 
/../cf-acceptance-tests/docker/docker_lifecycle.go:30

[Fail] [docker] Docker Application Lifecycle [JustBeforeEach] running a docker app without a start command when env vars are set with 'cf set-env' prefers the env vars from cf set-env over those in the Dockerfile 
/../cf-acceptance-tests/docker/docker_lifecycle.go:30

Ran 92 of 211 Specs in 3150.533 seconds
FAIL! -- 82 Passed | 10 Failed | 1 Pending | 118 Skipped
```

**Comment by jbuns** [comment]
After enabling diego_docker, got more tests to pass.

Latest results:
```
Summarizing 5 Failures:

[Fail] [apps] Buildpack cache [It] uses the buildpack cache after first staging 
/Users/jeffreybunagan/lahat/workspace/cf-acceptance-tests/apps/buildpack_cache.go:144

[Fail] [tcp routing] TCP Routing external ports [It] maps a single external port to an application's container port 
/Users/jeffreybunagan/lahat/workspace/cf-acceptance-tests/tcp_routing/tcp_routing.go:74

[Fail] [tcp routing] TCP Routing external ports with a second external port [It] maps both ports to the same application 
/Users/jeffreybunagan/lahat/workspace/cf-acceptance-tests/tcp_routing/tcp_routing.go:127

[Fail] [tcp routing] TCP Routing external ports with two different apps [It] maps single external port to both applications 
/Users/jeffreybunagan/lahat/workspace/cf-acceptance-tests/tcp_routing/tcp_routing.go:112

[Fail] [v3] buildpack With a single buildpack app [It] uses buildpack cache for staging 
/Users/jeffreybunagan/lahat/workspace/cf-acceptance-tests/v3/buildpacks.go:108

Ran 92 of 211 Specs in 2854.609 seconds
FAIL! -- 87 Passed | 5 Failed | 1 Pending | 118 Skipped
```

**Comment by jimmykarily** [comment]
Tcp routing doesn't seem to work. We tried with @jbuns to deploy the fixture app manually and follow the same steps like the test in order to setup a tcp route. Turns out that the route is never registered thus the haproxy configuration inside the tcp_router pod never gets updated. We compared the results between a (working) diego deployment and Eirini using these steps:

```# https://docs.cloudfoundry.org/adminguide/troubleshooting_tcp_routing.html                                                                                                                   

- First make sure you add externalIPs to the uaa-0 service so you can talk to it
- Install uaac: `gem install cf-uaac`
- Find the tcp_emitter secret: `kubectl get secrets -n scf var-uaa-clients-tcp-emitter-secret -o json | jq -r .data.password | base64 -d`
- Set the target: `/usr/lib64/ruby/gems/2.5.0/gems/cf-uaac-4.2.0/bin/uaac target --skip-ssl-validation https://uaa.172.17.0.3.omg.howdoi.website:8443`
- Authenticate: `/usr/lib64/ruby/gems/2.5.0/gems/cf-uaac-4.2.0/bin/uaac token client get tcp_emitter` (use the secret you found above)
- Get a token: `/usr/lib64/ruby/gems/2.5.0/gems/cf-uaac-4.2.0/bin/uaac context` (copy the token)
- Set the TOKEN variable: `export TOKEN=the_token_you_copied`
- Get the routes: `curl api.172.17.0.3.omg.howdoi.website/routing/v1/tcp_routes -H "Authorization: bearer ${TOKEN}"`

Example output from a working diego deployment:

[{"router_group_guid":"7976de96-9cbd-419e-766b-f4e65c8cd53e","backend_port":61001,"backend_ip":"10.32.0.26","port":20001,"modification_tag":{"guid":"50fdd0c2-600b-4ad7-6301-e60147edd598","index":283},"ttl":120,"isolation_segment":""},{"router_group_guid":"7976de96-9cbd-419e-766b-f4e65c8cd53e","backend_port":61001,"backend_ip":"10.32.0.26","port":20005,"modification_tag":{"guid":"64094981-1083-4f5d-7172-1bcbe21481e3","index":490},"ttl":120,"isolation_segment":""}]


This is how the haproxy configuration gets updates inside the tcp_router pod (`ps aux | more` to find the path to tha haproxy.conf).```

The result for Eirini is an empty Array : `[]`.

**Comment by jimmykarily** [comment]
Turns out Eirini doesn't support tcp routing yet: https://cloudfoundry.slack.com/archives/C8RU3BZ26/p1595429386415200
We should then just disable those tests.

Relevant link for what's coming next: https://github.com/cloudfoundry-incubator/eirini/issues/72 (in case someone wants to pursue this more).

**Comment by jimmykarily** [comment]
Regarding the buildpack cache failing test, this env variable has to be set somewhere: https://github.com/cloudfoundry-incubator/eirini-staging/blob/master/eirini_models.go#L21
(It all starts here: https://github.com/cloudfoundry-incubator/eirini-staging/blob/master/builder/runner.go#L49)
The cache dir probably gets cleaned up because it is not defined as "needed cache" through that env var. I described a staging pod and it doesn't have the EIRINI_BUILD_ARTIFACTS_CACHE_DIR var set and this code doesn't complain: https://github.com/cloudfoundry-incubator/eirini-staging/blob/master/cmd/executor/executor.go#L26)

Checking relevant lines with `git blame`, it seems that buildpack caching was implemented ~4 months ago: https://github.com/cloudfoundry-incubator/eirini-staging/commit/f64ac536b6077882aef38bf8e72180d7ca86c7c9 . 

In the 1.5.0 branch (which is what we use right now) code doesn't complain about missing env vars: https://github.com/cloudfoundry-incubator/eirini-staging/blob/1.5.0/cmd/executor/executor.go

We will probably get this test fixed for free after we upgrade Eirini: https://github.com/cloudfoundry-incubator/kubecf/issues/843

We can either disable the test of just let it fail until we complete the Eirini bump.

**Comment by jimmykarily** [comment]
We discussed some ideas to fix this:
https://github.com/jimmykarily/cf-acceptance-tests/compare/master..fix_eirini_cats#diff-732c88eb5fd838cc0fb2332e15279683R194

here: https://cloudfoundry.slack.com/archives/CQ2U3L6DC/p1595577637235400

**Comment by jbuns** [comment]
Watching this for a resolution:
https://github.com/cloudfoundry-incubator/kubecf/blob/master/doc/cf_deployment/bump.md#bump-cats-release
Or until config changes eirini bumps catapult

**Comment by jimmykarily** [comment]
I managed to get green CATs with the steps below.

## Install kubecf from master (sha: #91f19111)

```
$ export MAGIC_DNS_SERVICE=omg.howdoi.website
$ export EIRINI_FEATURE=true
$ make kind-start all
```

## Clone the CATs

```
$ git clone git git@github.com:cloudfoundry/cf-acceptance-tests.git
$ cd cf-acceptance-tests
$ git co cf13.8
```

## Apply changes to CATs

The changes below need to be properly upstreamed but for now we need these to make it work with our stack and the latest cf cli.

```
$ cat > patch.patch <<EOF
diff --git a/apps/admin_buildpack_lifecycle.go b/apps/admin_buildpack_lifecycle.go
index bedeac63..8616384e 100644
--- a/apps/admin_buildpack_lifecycle.go
+++ b/apps/admin_buildpack_lifecycle.go
@@ -271,7 +271,7 @@ exit 1
 
 		Expect(push).To(Exit(0))
 		appOutput := cf.Cf("app", appName).Wait()
-		Expect(appOutput).To(Say("buildpacks?:\\s+Simple"))
+		Expect(appOutput).To(Say("buildpacks?:.*\\n.+\\n.*Simple"))
 	}
 
 	itDoesNotDetectForEmptyApp := func() {
@@ -344,7 +344,7 @@ exit 1
 			Expect(cf.Cf("push", appName, "-b", buildpackName, "-m", DEFAULT_MEMORY_LIMIT, "-p", appPath).Wait(Config.CfPushTimeoutDuration())).To(Exit(0))
 
 			appOutput := cf.Cf("app", appName).Wait()
-			Expect(appOutput).To(Say("buildpacks?:\\s+" + buildpackName))
+			Expect(appOutput).To(Say("buildpacks?:.*\\n.+\\n.*" + buildpackName))
 		})
 
 		It("fails if the specified buildpack is disabled", func() {
diff --git a/helpers/config/config_struct.go b/helpers/config/config_struct.go
index 05880eb9..5ee5883e 100644
--- a/helpers/config/config_struct.go
+++ b/helpers/config/config_struct.go
@@ -222,7 +222,7 @@ func getDefaults() config {
 
 	defaults.NamePrefix = ptrToString("CATS")
 
-	defaults.Stacks = &[]string{"cflinuxfs3"}
+	defaults.Stacks = &[]string{"sle15"}
 	return defaults
 }
 
@@ -656,8 +656,8 @@ func validateStacks(config *config) error {
 	}
 
 	for _, stack := range config.GetStacks() {
-		if stack != "cflinuxfs3" {
-			return fmt.Errorf("* Invalid configuration: unknown stack '%s'. Only 'cflinuxfs3' is supported for the 'stacks' property", stack)
+		if stack != "sle15" {
+			return fmt.Errorf("* Invalid configuration: unknown stack '%s'. Only 'sle15' is supported for the 'stacks' property", stack)
 		}
 	}
EOF

$ git apply patch.patch

```

## Get latest cf cli v7

https://github.com/cloudfoundry/cli/blob/master/doc/installation-instructions/installation-instructions-v7.md#installers-and-compressed-binaries

(I got green CATs with this version: cf version 7.1.0+4c3168f9a.2020-09-09)

## Create cats.json

Get the IP of your kind container:

````
$ export kind_ip=$(docker inspect kubecf-control-plane | jq -r '.[0]["NetworkSettings"]["IPAddress"]')
```

Get the admin password:

```
$ export admin_password=$(kubectl get secrets -n kubecf var-cf-admin-password -o json | jq -r .data.password)
```

Login to cf (to enable docker feature):

```
$ cf api --skip-ssl-validation https://api.${kind_ip}.omg.howdoi.website
$ cf login (user: admin, password: $admin_password)
```

Enable docker feature (needed?):

```
$ cf enable-feature-flag diego_docker
```

Create cats.json:

```
$ cat > cats.json <<EOF
{
  "api": "api.${kind_ip}.omg.howdoi.website",
  "apps_domain": "${kind_ip}.omg.howdoi.website",
  "admin_user": "admin",
  "admin_password": "${admin_password}",
  "artifacts_directory": "logs",
  "skip_ssl_validation": true,
  "timeout_scale": 4,
  "use_http": false,
  "use_log_cache": true,
  "include_apps": true,
  "include_backend_compatibility": false,
  "include_capi_no_bridge": false,
  "include_container_networking": false,
  "credhub_mode": "skip-tests",
  "credhub_client": "credhub_admin_client",
  "credhub_secret": "..",
  "include_detect": false,
  "include_docker": true,
  "include_internet_dependent": false,
  "include_internetless": false,
  "include_isolation_segments": false,
  "include_private_docker_registry": false,
  "include_route_services": false,
  "include_routing": false,
  "include_tcp_routing": false,
  "include_routing_isolation_segments": false,
  "include_security_groups": false,
  "include_service_discovery": false,
  "include_services": false,
  "include_service_instance_sharing": false,
  "include_ssh": false,
  "include_sso": false,
  "include_tasks": false,
  "include_v3": true,
  "include_zipkin": false,
  "include_credhub": false,
  "include_volume_services": false,
  "stacks": [
    "sle15"
  ]
}
EOF
```

## Follow the instruction in the cf-acceptance-tests README

```
$ cf install-plugin -r CF-Community "log-cache"
$ ./bin/update_submodules
$ source .envrc
$ go mode vendor
```

## Run the tests

If you use too many ginkgo nodes you may get failures because of low resources.
Better be conservative. It will take more time to finish but the results will
reflect reality better and you won't need to run them one by one to see if they
really fail.

```
$ ./bin/test -node=1
```

**Comment by fargozhu** [comment]
@jeff-hobbs @jimmykarily closing this one. Feel free to disagree and to reopen again.
