### ISSUE TITLE
bazel build target for kubecf fails

### ISSUE THREAD

**Issue by qu1queee** [cloudfoundry-incubator/kubecf#1112]
**Describe the bug**
```sh
INFO: Analyzed target //deploy/bundle:cf_operator_chart (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //deploy/bundle:cf_operator_chart up-to-date:
  bazel-bin/deploy/bundle/cf-operator.tgz
INFO: Elapsed time: 0.607s, Critical Path: 0.47s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Analyzed target //deploy/helm/kubecf:version (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/encalada/workspace/in_house/bkcf/kubecf/deploy/helm/kubecf/BUILD.bazel:97:1: Generating sample values.yaml bazel-out/darwin-fastbuild/bin/deploy/helm/kubecf/sample-values.yaml failed (Exit 1) create_sample_values.rb failed: error executing command rules/kubecf/create_sample_values.rb deploy/helm/kubecf/values.yaml bazel-out/darwin-fastbuild/bin/deploy/helm/kubecf/sample-values.yaml

Use --sandbox_debug to see verbose messages from the sandbox
rules/kubecf/create_sample_values.rb:65:in `start_pos': undefined local variable or method `start_line' for #<Psych::Nodes::Scalar:0x00007fab11838e20> (NameError)
Did you mean?  start_pos
	from rules/kubecf/create_sample_values.rb:161:in `block (2 levels) in determine_node_parents'
	from rules/kubecf/create_sample_values.rb:158:in `each'
	from rules/kubecf/create_sample_values.rb:158:in `block in determine_node_parents'
	from rules/kubecf/create_sample_values.rb:157:in `each'
	from rules/kubecf/create_sample_values.rb:157:in `determine_node_parents'
	from rules/kubecf/create_sample_values.rb:563:in `process'
	from rules/kubecf/create_sample_values.rb:660:in `<main>'
Target //deploy/helm/kubecf:version failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.368s, Critical Path: 0.22s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**To Reproduce**
do a `bazel build //deploy/helm/kubecf:version`

**Expected behavior**
no errors..

**Environment**
 - CF Version
 - Component/Plugin Name
 - Others

**Additional context**
```sh
$ ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin18]
```
running on a macOS

**Comment by jandubois** [comment]
I cannot repro this problem (on latest `master`):

```
$ bazel build //deploy/helm/kubecf:version
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //deploy/helm/kubecf:version (37 packages loaded, 447 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /private/var/tmp/_bazel_jan/5a31e95fe5f252a5db1531c479ebe508/sandbox
Target //deploy/helm/kubecf:version up-to-date:
  bazel-bin/deploy/helm/kubecf/version.txt
INFO: Elapsed time: 11.881s, Critical Path: 1.59s
INFO: 9 processes: 9 darwin-sandbox.
INFO: Build completed successfully, 12 total actions

$ ruby --version
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
```

Whenever I ran into spurious Bazel errors (especially if the error included the string `--sandbox_debug`), I would first clean the Bazel cache and try again:

```
$ bazel clean --expunge
INFO: Starting clean.
```

I would think that if Bazel worked correctly, this should never make a difference, but it fixed my problems multiple times...

**Comment by fargozhu** [comment]
@qu1queee I am closing this one but feel free to open it if you have more details or logs about it.
