### ISSUE TITLE
kubecf-diego-api-0  pod is crashing and cannot be started

### ISSUE THREAD

**Issue by cmoulliard** [cloudfoundry-incubator/kubecf#483]
**Describe the bug**
It seems that the installation of kubecf fails on kubernetes 1.16 as the pod of `kubecf-diego-api-0` is crashing and by consequence, kubecf cannot be installed correctly
```
kc -n kubecf get pods
NAME                                            READY   STATUS             RESTARTS   AGE
kubecf-adapter-0                                4/4     Running            0          13m
kubecf-api-0                                    0/15    Init:30/63         0          12m
kubecf-auctioneer-0                             0/4     Init:5/9           0          12m
kubecf-bosh-dns-59cd464989-j77bp                1/1     Running            0          13m
kubecf-bosh-dns-59cd464989-vzlfb                1/1     Running            0          13m
kubecf-cc-worker-0                              0/4     Init:5/9           0          12m
kubecf-credhub-0                                0/6     Init:7/13          0          12m
kubecf-database-0                               0/2     Pending            0          22m
kubecf-database-seeder-ce64fc22d00bdf73-p5rz9   1/2     Running            0          23m
kubecf-diego-api-0                              4/6     CrashLoopBackOff   12         12m
kubecf-diego-cell-0                             0/7     Init:8/20          0          12m
kubecf-doppler-0                                0/9     Init:7/16          0          12m
kubecf-log-api-0                                0/7     Init:6/13          0          12m
kubecf-nats-0                                   4/4     Running            0          12m
kubecf-router-0                                 0/5     Init:5/11          0          12m
kubecf-routing-api-0                            0/4     Init:5/10          0          12m
kubecf-scheduler-0                              0/10    Init:8/19          0          12m
kubecf-singleton-blobstore-0                    0/6     Pending            0          12m
kubecf-tcp-router-0                             0/5     Init:5/11          0          12m
kubecf-uaa-0                                    0/7     Init:8/15          0          12m
```

**To Reproduce**
- Setup a kubernetes cluster : 1.16
- Install the cf-operator and kubecf using helm
- Execute these commands
```
kc create ns cf-operator
helm repo add quarks https://cloudfoundry-incubator.github.io/quarks-helm/
helm search repo quarks
helm install cf-operator quarks/cf-operator --namespace cf-operator --set "global.operator.watchNamespace=kubecf"
NODE_NAME=k03-k116
node_ip=$(kubectl get node ${NODE_NAME} \
  --output jsonpath='{ .status.addresses[?(@.type == "InternalIP")].address }')
cat << _EOF_  > values.yaml
system_domain: ${node_ip}.nip.io
services:
  router:
    externalIPs:
    - ${node_ip}
kube:
  service_cluster_ip_range: 0.0.0.0/0
  pod_cluster_ip_range: 0.0.0.0/0
_EOF_

helm install kubecf --namespace kubecf --values values.yaml https://github.com/cloudfoundry-incubator/kubecf/releases/download/v1.0.0/kubecf-v1.0.0.tgz
```

**Comment by cmoulliard** [comment]
The log of the kubernetes diego api reports such error 
```
│ loggregator-agent-loggregator-agent 2020/03/12 17:27:11.932061 failed to connect: unable to lookup a log consumer                                                                                │
│ loggregator-agent-loggregator-agent 2020/03/12 17:27:11.932031 failed to connect: unable to lookup a log consumer                                                                                │
│ loggregator-agent-loggregator-agent 2020/03/12 17:27:11.932047 failed to connect: unable to lookup a log consumer                                                                                │
│ loggregator-agent-loggregator-agent 2020/03/12 17:27:12.930292 failed to connect: unable to lookup a log consumer                                                                                │
│ loggregator-agent-loggregator-agent 2020/03/12 17:27:12.930320 failed to connect: unable to lookup a log consumer                                                                                │
│ loggregator-agent-loggregator-agent 2020/03/12 17:27:12.930324 failed to connect: unable to lookup a log consumer                                                                                │
│ loggregator-agent-loggregator-agent 2020/03/12 17:27:12.930354 failed to connect: unable to lookup a log consumer                                                                                │
│ loggregator-agent-loggregator-agent 2020/03/12 17:27:12.930328 failed to connect: unable to lookup a log consumer                                                                                │
│ loggregator-agent-loggregator-agent 2020/03/12 17:27:13.929634 failed to connect: unable to lookup a log consumer                                                                                │
│ loggregator-agent-loggregator-agent 2020/03/12 17:27:13.929641 failed to connect: unable to lookup a log consumer                                                                                │
│ loggregator-agent-loggregator-agent 2020/03/12 17:27:13.929658 failed to connect: unable to lookup a log consumer                                                                                │
│ loggregator-agent-loggregator-agent 2020/03/12 17:27:13.929649 failed to connect: unable to lookup a log consumer
```
This error seems to be reported by the init container `locket`

```
│ {"timestamp":"2020-03-12T17:27:18.210298805Z","level":"fatal","source":"locket","message":"locket.sql-failed-to-connect","data":{"error":"dial tcp 10.101.182.26:3306: connect: connection refus │
│ panic: dial tcp 10.101.182.26:3306: connect: connection refused                                                                                                                                  │
│ goroutine 1 [running]:                                                                                                                                                                           │
│ code.cloudfoundry.org/lager.(*logger).Fatal(0xc0001463c0, 0xb05020, 0x15, 0xbcf8c0, 0xc0002ae050, 0x0, 0x0, 0x0)                                                                                 │
│     /var/vcap/source/locket/src/code.cloudfoundry.org/lager/logger.go:162 +0x582                                                                                                                 │
│ main.main()                                                                                                                                                                                      │
│     /var/vcap/source/locket/src/code.cloudfoundry.org/locket/cmd/locket/main.go:80 +0x1e54
```

**Comment by cmoulliard** [comment]
The previous error is related to the fact that the pod reunning the database on the port 3306 was not started due to an issue with the `PV/PVC`. After changing the size of the `PV` to `20Gi` and `100Gi`, than I have been able to start the pod of diego api

But now I suffer from another issue with the pod of `kubecf-uaa-0` and container `cf-cli-6-linux-uaa-internal-security-group-setup`

```
Logs(kubecf/kubecf-uaa-0:cf-cli-6-linux-uaa-internal-security-group-setup) ───────────────────────────────────────────────────────────┐
│                                                                                                                                               Autoscroll: On   FullScreen: Off  Wrap: Off        │
│ Waiting for the API to be accessible...                                                                                                                                                          │
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                  │
│                                  Dload  Upload   Total   Spent    Left  Speed                                                                                                                    │
│   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0                                     │
│ curl: (60) SSL certificate problem: unable to get local issuer certificate                                                                                                                       │
│ More details here: https://curl.haxx.se/docs/sslcerts.html                                                                                                                                       │
│ curl failed to verify the legitimacy of the server and therefore could not                                                                                                                       │
│ establish a secure connection to it. To learn more about this situation and                                                                                                                      │
│ how to fix it, please visit the web page mentioned above.
```

**Comment by f0rmiga** [comment]
@cmoulliard Thanks for reporting this. It should get fixed with https://github.com/cloudfoundry-incubator/kubecf/issues/480.

**Comment by cmoulliard** [comment]
> It should get fixed with #480.

Is there a workaround ? @f0rmiga

**Comment by ylecleach** [comment]
I have the same issue. unable to install v1.0.0 of kubecf. could you please fix it.
I am managing to install it on IBM Cloud IKS.
What is the minimum cluster requirement for a demo. I am currently using a single worker 4vCPU 16 Gb RAM.

**Comment by cmoulliard** [comment]
> worker 4vCPU 16 Gb RAM.

16GB should be enough from the test I did using `kind` + k8s 116 and kubecf deployed using feature eirini enabled

**Comment by f0rmiga** [comment]
@cmoulliard We don't have any workarounds for this problem. The fix should land with https://github.com/cloudfoundry-incubator/kubecf/pull/485. I'll leave this issue open until you try it out.

**Comment by fargozhu** [comment]
@cmoulliard @ylecleach @f0rmiga kubecf 1.0.1 released and #485 is included. Let me know if you're still having problems or if I close this one.

**Comment by cmoulliard** [comment]
@fargozhu Deigo API is running but I'm blocked now by the same issue reported for the ticket #484 
and which is 
```
kc logs -n kubecf pod/kubecf-diego-cell-0 -c rep-rep
{"timestamp":"2020-03-20T12:40:13.361042436Z","level":"info","source":"rep","message":"rep.wait-for-garden.ping-garden","data":{"initialTime:":"2020-03-20T12:40:13.36086648Z","session":"1","wait-time-ns:":174419}}
{"timestamp":"2020-03-20T12:40:13.363909300Z","level":"info","source":"rep","message":"rep.wait-for-garden.ping-garden-success","data":{"initialTime:":"2020-03-20T12:40:13.36086648Z","session":"1","wait-time-ns:":3041195}}
{"timestamp":"2020-03-20T12:40:13.363977419Z","level":"info","source":"rep","message":"rep.executor-fetching-containers-to-destroy","data":{}}
{"timestamp":"2020-03-20T12:40:13.364891164Z","level":"info","source":"rep","message":"rep.executor-fetched-containers-to-destroy","data":{"num-containers":0}}
{"timestamp":"2020-03-20T12:40:13.682360532Z","level":"info","source":"rep","message":"rep.initial-capacity","data":{"capacity":{"memory_mb":7792,"disk_mb":67353,"containers":249}}}
{"timestamp":"2020-03-20T12:40:14.074291388Z","level":"error",
"source":"rep",
"message":"rep.failed-to-initialize-executor",
"data":{"error":"runc run: exit status 1: 
container_linux.go:346: starting container process caused 
\"process_linux.go:319: getting the final child's pid from pipe caused \\\"EOF\\\"\""}}
[snowdrop@h02-k115 temp]$
```

**Comment by cmoulliard** [comment]
FYI, If I select the `Features/Eirini` to install the helm chart

```
cat values.yaml
system_domain: 95.217.134.208.nip.io
services:
  router:
    externalIPs:
    - 95.217.134.208
features:
  eirini:
    enabled: true
kube:
  service_cluster_ip_range: 0.0.0.0/0
  pod_cluster_ip_range: 0.0.0.0/0
```

then `diego-api` is still failing to start as the container `locket:locket` is reporting this error `dial tcp 10.96.149.148:3306: connect: connection refuse │
│ panic: dial tcp 10.96.149.148:3306: connect: connection refused`

See log hereafter
```
│                                                                                                                                                Autoscroll: On   FullScreen: Off  Wrap: Off        │
│ {"timestamp":"2020-03-20T13:46:01.448340274Z","level":"fatal","source":
"locket","message":"locket.sql-failed-to-connect",
"data":{"error":"dial tcp 10.96.149.148:3306: connect: connection refuse │
│ panic: dial tcp 10.96.149.148:3306: connect: connection refused                                                                                                                                   │
│ goroutine 1 [running]:                                                                                                                                                                            │
│ code.cloudfoundry.org/lager.(*logger).Fatal(0xc000122480, 0xb05020, 0x15, 0xbcf8c0, 0xc000143f40, 0x0, 0x0, 0x0)                                                                                  │
│     /var/vcap/source/locket/src/code.cloudfoundry.org/lager/logger.go:162 +0x582                                                                                                                  │
│ main.main()                                                                                                                                                                                       │
│     /var/vcap/source/locket/src/code.cloudfoundry.org/locket/cmd/locket/main.go:80 +0x1e54                                                                                                        │
│ <STREAM> closed                                                                                                                                                                                   │
│
```

**Comment by viovanov** [comment]
@cmoulliard 

```
panic: dial tcp 10.96.149.148:3306: connect: connection refused
```

Locket needs to connect to a database. Are you using the internal DB, or an external one?
mysql or postgres?

**Comment by cmoulliard** [comment]
> Locket needs to connect to a database. Are you using the internal DB, or an external one?
> mysql or postgres?

There was an issue with my PVC. This is fixed and kubecf 1.0.1 works perfectly on my kubernetes cluster 1.15. I tested it with 2 Applications: 
- cf push using a docker image
- cf push of a spring boot application (=> buildpack)

**Comment by cmoulliard** [comment]
IT can be closed for me @fargozhu

**Comment by ylecleach** [comment]
using IBM IKS 117 and kubecf 101 I have still installation issue.
I think I have found a great findings on the pod kubecf-database-0 below 

Events:
  Type     Reason     Age                  From                   Message
  ----     ------     ----                 ----                   -------
  Warning  Unhealthy  2m (x600 over 101m)  kubelet, 10.215.10.47  Readiness probe failed: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

I know that IBM IKS POD Security Policy is very strict for security sakes. 

Do you have any clues to configure KubeCF 101 on such a cluster ?

Thank you

**Comment by ylecleach** [comment]
@fargozhu : any update on my issue ?

**Comment by fargozhu** [comment]
@ylecleach I do think your issue is related to the original one so I kindly ask you to open a new bug so we can track all the community contributions and have a clean history.

**Comment by ylecleach** [comment]
ok I will do. thx

**Comment by kacperpabian** [comment]
was the bug opened? I experience the exact same think, would like to know the solution

**Comment by jandubois** [comment]
> was the bug opened?

I believe it is #555
